import * as yaml from 'yaml';
import { Workflow } from './workflow';

/**
 * Interface for objects that can be synthesized to a plain object representation
 */
export interface ISynth {
  /**
   * Synthesize this object to a plain object that can be serialized
   */
  synth(): any;
}

/**
 * Synthesize a workflow to YAML string
 */
export function synth(workflow: Workflow): string {
  // Validate the construct tree before synthesizing
  const errors = workflow.node.validate();
  if (errors.length > 0) {
    throw new Error(`Validation errors:\n${errors.join('\n')}`);
  }

  const obj = workflow.synth();
  const yamlContent = yaml.stringify(obj);
  return `# this file was generated by a tool. DO NOT EDIT\n\n${yamlContent}`;
  // fs.writeFileSync(filePath, data, { encoding: 'utf8' });
}

